controller_list:
  - name: fake_end_effector_controller
    joints:
      - z
  - name: fake_end_effector_arm_controller
    joints:
      - theta_1
      - beta_1
      - gamma_1
      - theta_2
      - beta_2
      - gamma_2
      - theta_3
      - beta_3
      - gamma_3
      - x
      - y
      - z
initial:  # Define initial robot poses.
  - group: end_effector
    pose: home