end_effector_arm_1:
  kinematics_solver: omnid_kinematics/OmnidKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
end_effector_arm_2:
  kinematics_solver: omnid_kinematics/OmnidKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
end_effector_arm_3:
  kinematics_solver: omnid_kinematics/OmnidKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
object_platform_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005