controller_list:
  - name: all_arms_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - object_platform/x
      - object_platform/y
      - object_platform/z
      - object_platform/roll
      - object_platform/pitch
      - object_platform/yaw
      - robot_1/theta_1
      - robot_1/beta_1
      - robot_1/gamma_1
      - robot_1/theta_2
      - robot_1/beta_2
      - robot_1/gamma_2
      - robot_1/theta_3
      - robot_1/beta_3
      - robot_1/gamma_3
      - robot_1/x
      - robot_1/y
      - robot_1/z
      - robot_2/theta_1
      - robot_2/beta_1
      - robot_2/gamma_1
      - robot_2/theta_2
      - robot_2/beta_2
      - robot_2/gamma_2
      - robot_2/theta_3
      - robot_2/beta_3
      - robot_2/gamma_3
      - robot_2/x
      - robot_2/y
      - robot_2/z
      - robot_3/theta_1
      - robot_3/beta_1
      - robot_3/gamma_1
      - robot_3/theta_2
      - robot_3/beta_2
      - robot_3/gamma_2
      - robot_3/theta_3
      - robot_3/beta_3
      - robot_3/gamma_3
      - robot_3/x
      - robot_3/y
      - robot_3/z