# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - object_platform/x
    - object_platform/y
    - object_platform/z
    - object_platform/roll
    - object_platform/pitch
    - object_platform/yaw
    - robot_1/phi_1
    - robot_1/theta_1
    - robot_1/beta_1
    - robot_1/gamma_1
    - robot_1/phi_2
    - robot_1/theta_2
    - robot_1/beta_2
    - robot_1/gamma_2
    - robot_1/phi_3
    - robot_1/theta_3
    - robot_1/beta_3
    - robot_1/gamma_3
    - robot_1/x
    - robot_1/y
    - robot_1/z
    - robot_2/phi_1
    - robot_2/theta_1
    - robot_2/beta_1
    - robot_2/gamma_1
    - robot_2/phi_2
    - robot_2/theta_2
    - robot_2/beta_2
    - robot_2/gamma_2
    - robot_2/phi_3
    - robot_2/theta_3
    - robot_2/beta_3
    - robot_2/gamma_3
    - robot_2/x
    - robot_2/y
    - robot_2/z
    - robot_3/phi_1
    - robot_3/theta_1
    - robot_3/beta_1
    - robot_3/gamma_1
    - robot_3/phi_2
    - robot_3/theta_2
    - robot_3/beta_2
    - robot_3/gamma_2
    - robot_3/phi_3
    - robot_3/theta_3
    - robot_3/beta_3
    - robot_3/gamma_3
    - robot_3/x
    - robot_3/y
    - robot_3/z
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []